version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"  # Frontend port
      - "8000:8000"  # Backend port
    environment:
      - BACKEND_PORT=8000
      - FRONTEND_PORT=3000
    volumes:
      # Mount logs directory for persistence
      - ./services/backend/logs:/app/services/backend/logs
      # Mount app settings for configuration without rebuild
      - ./services/frontend/appSettings.json:/app/services/frontend/appSettings.json
      # Optional: Mount source code for development (uncomment for live reload)
      # - ./services:/app/services
    working_dir: /app
    command: make dev 