version: '3.8'

services:
  app:
    build: 
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ..:/app:cached
      - /app/services/frontend/node_modules
      - /app/services/backend/.venv
      - ./services/frontend/appSettings.json:/app/services/frontend/appSettings.json
    ports:
      - "3000:3000"
      - "8000:8000"
    environment:
      - BACKEND_PORT=8000
      - FRONTEND_PORT=3000
    command: make dev
    working_dir: /app 